// <auto-generated />
using Epm.FarmRoots.ProductCatalogue.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Epm.FarmRoots.ProductCatalogue.Infrastructure.Migrations.ManufacturerDb
{
    [DbContext(typeof(ManufacturerDbContext))]
    [Migration("20240908173226_Manufacturer-Table Setup")]
    partial class ManufacturerTableSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Epm.FarmRoots.ProductCatalogue.Core.Entities.Manufacturer", b =>
                {
                    b.Property<int>("ManufactureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManufactureId"));

                    b.Property<int>("ManufactureDisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("ManufactureFeaturedStatus")
                        .HasColumnType("bit");

                    b.Property<string>("ManufactureName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ManufactureId");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            ManufactureId = 1,
                            ManufactureDisplayOrder = 0,
                            ManufactureFeaturedStatus = false,
                            ManufactureName = "Acer"
                        },
                        new
                        {
                            ManufactureId = 2,
                            ManufactureDisplayOrder = 0,
                            ManufactureFeaturedStatus = false,
                            ManufactureName = "Adidas"
                        },
                        new
                        {
                            ManufactureId = 3,
                            ManufactureDisplayOrder = 0,
                            ManufactureFeaturedStatus = false,
                            ManufactureName = "Apple"
                        },
                        new
                        {
                            ManufactureId = 4,
                            ManufactureDisplayOrder = 0,
                            ManufactureFeaturedStatus = false,
                            ManufactureName = "BOSS"
                        },
                        new
                        {
                            ManufactureId = 5,
                            ManufactureDisplayOrder = 0,
                            ManufactureFeaturedStatus = false,
                            ManufactureName = "BlackBerry"
                        },
                        new
                        {
                            ManufactureId = 6,
                            ManufactureDisplayOrder = 0,
                            ManufactureFeaturedStatus = false,
                            ManufactureName = "Casio"
                        },
                        new
                        {
                            ManufactureId = 7,
                            ManufactureDisplayOrder = 0,
                            ManufactureFeaturedStatus = false,
                            ManufactureName = "Converse"
                        },
                        new
                        {
                            ManufactureId = 8,
                            ManufactureDisplayOrder = 0,
                            ManufactureFeaturedStatus = false,
                            ManufactureName = "Daiber"
                        },
                        new
                        {
                            ManufactureId = 9,
                            ManufactureDisplayOrder = 0,
                            ManufactureFeaturedStatus = false,
                            ManufactureName = "Dell"
                        },
                        new
                        {
                            ManufactureId = 10,
                            ManufactureDisplayOrder = 0,
                            ManufactureFeaturedStatus = false,
                            ManufactureName = "EA Sports"
                        },
                        new
                        {
                            ManufactureId = 11,
                            ManufactureDisplayOrder = 0,
                            ManufactureFeaturedStatus = false,
                            ManufactureName = "HP"
                        },
                        new
                        {
                            ManufactureId = 12,
                            ManufactureDisplayOrder = 0,
                            ManufactureFeaturedStatus = false,
                            ManufactureName = "HTC"
                        },
                        new
                        {
                            ManufactureId = 13,
                            ManufactureDisplayOrder = 0,
                            ManufactureFeaturedStatus = false,
                            ManufactureName = "LG"
                        },
                        new
                        {
                            ManufactureId = 14,
                            ManufactureDisplayOrder = 0,
                            ManufactureFeaturedStatus = false,
                            ManufactureName = "MSI"
                        },
                        new
                        {
                            ManufactureId = 15,
                            ManufactureDisplayOrder = 0,
                            ManufactureFeaturedStatus = false,
                            ManufactureName = "Nike"
                        },
                        new
                        {
                            ManufactureId = 16,
                            ManufactureDisplayOrder = 0,
                            ManufactureFeaturedStatus = false,
                            ManufactureName = "Panasonic"
                        },
                        new
                        {
                            ManufactureId = 17,
                            ManufactureDisplayOrder = 0,
                            ManufactureFeaturedStatus = false,
                            ManufactureName = "Puma"
                        },
                        new
                        {
                            ManufactureId = 18,
                            ManufactureDisplayOrder = 0,
                            ManufactureFeaturedStatus = false,
                            ManufactureName = "Samsung"
                        },
                        new
                        {
                            ManufactureId = 19,
                            ManufactureDisplayOrder = 0,
                            ManufactureFeaturedStatus = false,
                            ManufactureName = "Sony"
                        },
                        new
                        {
                            ManufactureId = 20,
                            ManufactureDisplayOrder = 0,
                            ManufactureFeaturedStatus = false,
                            ManufactureName = "Wilson"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
