// <auto-generated />
using Epm.FarmRoots.ProductCatalogue.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Epm.FarmRoots.ProductCatalogue.Infrastructure.Migrations.ManufacturerDb
{
    [DbContext(typeof(ManufacturerDbContext))]
    [Migration("20240909105101_Updated the Manufacturer Names")]
    partial class UpdatedtheManufacturerNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Epm.FarmRoots.ProductCatalogue.Core.Entities.Manufacturer", b =>
                {
                    b.Property<int>("ManufactureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManufactureId"));

                    b.Property<int>("ManufactureDisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("ManufactureFeaturedStatus")
                        .HasColumnType("bit");

                    b.Property<string>("ManufactureName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ManufactureId");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            ManufactureId = 1,
                            ManufactureDisplayOrder = 0,
                            ManufactureFeaturedStatus = false,
                            ManufactureName = "Dole Food Company"
                        },
                        new
                        {
                            ManufactureId = 2,
                            ManufactureDisplayOrder = 0,
                            ManufactureFeaturedStatus = false,
                            ManufactureName = "Driscoll’s"
                        },
                        new
                        {
                            ManufactureId = 3,
                            ManufactureDisplayOrder = 0,
                            ManufactureFeaturedStatus = false,
                            ManufactureName = "Chiquita Brands International"
                        },
                        new
                        {
                            ManufactureId = 4,
                            ManufactureDisplayOrder = 0,
                            ManufactureFeaturedStatus = false,
                            ManufactureName = "Green Giant"
                        },
                        new
                        {
                            ManufactureId = 5,
                            ManufactureDisplayOrder = 0,
                            ManufactureFeaturedStatus = false,
                            ManufactureName = "The Little Potato Company"
                        },
                        new
                        {
                            ManufactureId = 6,
                            ManufactureDisplayOrder = 0,
                            ManufactureFeaturedStatus = false,
                            ManufactureName = "Tyson Foods"
                        },
                        new
                        {
                            ManufactureId = 7,
                            ManufactureDisplayOrder = 0,
                            ManufactureFeaturedStatus = false,
                            ManufactureName = "Danone"
                        },
                        new
                        {
                            ManufactureId = 8,
                            ManufactureDisplayOrder = 0,
                            ManufactureFeaturedStatus = false,
                            ManufactureName = "Coca-Cola"
                        },
                        new
                        {
                            ManufactureId = 9,
                            ManufactureDisplayOrder = 0,
                            ManufactureFeaturedStatus = false,
                            ManufactureName = "PepsiCo"
                        },
                        new
                        {
                            ManufactureId = 10,
                            ManufactureDisplayOrder = 0,
                            ManufactureFeaturedStatus = false,
                            ManufactureName = "General Mills"
                        },
                        new
                        {
                            ManufactureId = 11,
                            ManufactureDisplayOrder = 0,
                            ManufactureFeaturedStatus = false,
                            ManufactureName = "Lay's"
                        },
                        new
                        {
                            ManufactureId = 12,
                            ManufactureDisplayOrder = 0,
                            ManufactureFeaturedStatus = false,
                            ManufactureName = "Haldiram's"
                        },
                        new
                        {
                            ManufactureId = 13,
                            ManufactureDisplayOrder = 0,
                            ManufactureFeaturedStatus = false,
                            ManufactureName = "Dettol"
                        },
                        new
                        {
                            ManufactureId = 14,
                            ManufactureDisplayOrder = 0,
                            ManufactureFeaturedStatus = false,
                            ManufactureName = "Nestlé"
                        },
                        new
                        {
                            ManufactureId = 15,
                            ManufactureDisplayOrder = 0,
                            ManufactureFeaturedStatus = false,
                            ManufactureName = "Dove"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
